import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.environ.get("PROJECTK_DB_PATH", "/tmp/projectk_local.db")
API_HOST = os.environ.get("PROJECTK_API_HOST", "127.0.0.1")
API_PORT = int(os.environ.get("PROJECTK_API_PORT", "8081"))
WEB_HOST = os.environ.get("PROJECTK_WEB_HOST", "127.0.0.1")
WEB_PORT = int(os.environ.get("PROJECTK_WEB_PORT", "8082"))

TELEGRAM_BOT_TOKEN = os.environ.get("PROJECTK_TELEGRAM_BOT_TOKEN", "").strip()
TELEGRAM_CHAT_ID = os.environ.get("PROJECTK_TELEGRAM_CHAT_ID", "").strip()
TELEGRAM_MAX_RETRIES = int(os.environ.get("PROJECTK_TELEGRAM_MAX_RETRIES", "3"))
TELEGRAM_OWNER_CHAT_ID = os.environ.get("PROJECTK_TELEGRAM_OWNER_CHAT_ID", "").strip()
DASHBOARD_URL = os.environ.get("PROJECTK_DASHBOARD_URL", f"http://127.0.0.1:{WEB_PORT}").strip()

VAULT_PASSPHRASE = os.environ.get("PROJECTK_VAULT_PASSPHRASE", "").strip()

EXECUTOR_MODE = os.environ.get("PROJECTK_EXECUTOR_MODE", "stub").strip().lower()
EXECUTOR_POLL_SECONDS = int(os.environ.get("PROJECTK_EXECUTOR_POLL_SECONDS", "10"))
EXECUTOR_MARKET_MIN_BUY_USDC = float(os.environ.get("PROJECTK_EXECUTOR_MARKET_MIN_BUY_USDC", "1"))
EXECUTOR_MIN_SOURCE_NOTIONAL_USDC = float(
    os.environ.get("PROJECTK_EXECUTOR_MIN_SOURCE_NOTIONAL_USDC", "20")
)
EXECUTOR_BALANCE_FAIL_COOLDOWN_SECONDS = int(
    os.environ.get("PROJECTK_EXECUTOR_BALANCE_FAIL_COOLDOWN_SECONDS", "300")
)
EXECUTOR_OPEN_ORDER_CANCEL_AFTER_SECONDS = int(
    os.environ.get("PROJECTK_EXECUTOR_OPEN_ORDER_CANCEL_AFTER_SECONDS", "60")
)
BLOCKED_ALERT_COOLDOWN_SECONDS = int(
    os.environ.get("PROJECTK_BLOCKED_ALERT_COOLDOWN_SECONDS", "3600")
)
POLYMARKET_HOST = os.environ.get("PROJECTK_POLYMARKET_HOST", "https://clob.polymarket.com").strip()
POLYMARKET_CHAIN_ID = int(os.environ.get("PROJECTK_POLYMARKET_CHAIN_ID", "137"))
POLYMARKET_SIGNATURE_TYPE = int(os.environ.get("PROJECTK_POLYMARKET_SIGNATURE_TYPE", "0"))
POLYMARKET_MAX_SPREAD_BPS = int(os.environ.get("PROJECTK_POLYMARKET_MAX_SPREAD_BPS", "200"))

RPC_URL = os.environ.get("PROJECTK_RPC_URL", "").strip()
USDC_TOKEN_ADDRESS = os.environ.get(
    "PROJECTK_USDC_TOKEN_ADDRESS",
    "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",
).strip()
WATCHER_POLL_SECONDS = int(os.environ.get("PROJECTK_WATCHER_POLL_SECONDS", "10"))
WATCHER_CONFIRMATIONS = int(os.environ.get("PROJECTK_WATCHER_CONFIRMATIONS", "2"))
WATCHER_MAX_BLOCK_RANGE = int(os.environ.get("PROJECTK_WATCHER_MAX_BLOCK_RANGE", "200"))
WATCHER_MAX_LAG_BLOCKS = int(os.environ.get("PROJECTK_WATCHER_MAX_LAG_BLOCKS", "600"))
WATCHER_POLL_MIN_SECONDS = int(os.environ.get("PROJECTK_WATCHER_POLL_MIN_SECONDS", "5"))
WATCHER_POLL_MAX_SECONDS = int(os.environ.get("PROJECTK_WATCHER_POLL_MAX_SECONDS", "10"))
WATCHER_BACKOFF_ERROR_STREAK = int(os.environ.get("PROJECTK_WATCHER_BACKOFF_ERROR_STREAK", "2"))
WATCHER_BACKOFF_SLOW_TICK_MS = int(os.environ.get("PROJECTK_WATCHER_BACKOFF_SLOW_TICK_MS", "4000"))
WATCHER_RECOVERY_HEALTHY_TICKS = int(os.environ.get("PROJECTK_WATCHER_RECOVERY_HEALTHY_TICKS", "6"))
WATCHER_EXCHANGES = os.environ.get(
    "PROJECTK_WATCHER_EXCHANGES",
    ",".join(
        [
            "0xC5d563A36AE78145C45a50134d48A1215220f80a",
            "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E",
        ]
    ),
).strip()

CLAIM_POLL_SECONDS = int(os.environ.get("PROJECTK_CLAIM_POLL_SECONDS", "60"))
CLAIM_ENABLE_AUTO_REDEEM = os.environ.get("PROJECTK_CLAIM_ENABLE_AUTO_REDEEM", "0").strip() == "1"
CLAIM_MIN_NET_SHARES = float(os.environ.get("PROJECTK_CLAIM_MIN_NET_SHARES", "0.01"))
CLAIM_CTF_CONTRACT = os.environ.get(
    "PROJECTK_CLAIM_CTF_CONTRACT",
    "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045",
).strip()
